//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyDetailsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class conversation
    {
        public int id { get; set; }
        public int pid { get; set; }
        public string senderMail { get; set; }
        public string customermail { get; set; }
        public string text { get; set; }
        public System.DateTime date { get; set; }
    }
}
