//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyDetailsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class propertyDetail
    {
        public int propertyID { get; set; }
        public int adminID { get; set; }
        public string adminName { get; set; }
        public string propertyName { get; set; }
        public string Location { get; set; }
        public int price { get; set; }
        public string category { get; set; }
        public string imageName { get; set; }
        public Nullable<int> Rating { get; set; }
    }
}
