//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapstoneProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class propertyReservation
    {
        public int reservationId { get; set; }
        public int propertyid { get; set; }
        public int userid { get; set; }
        public int adminid { get; set; }
        public string propertyname { get; set; }
        public System.DateTime checkin { get; set; }
        public System.DateTime checkout { get; set; }
        public string confirmation { get; set; }
    }
}
